//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliArchive.Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actor
    {
        public Actor()
        {
            this.AmateurFights = new HashSet<AmateurFight>();
            this.ExibitionFights = new HashSet<ExibitionFight>();
            this.Fights = new HashSet<Fight>();
            this.Fights1 = new HashSet<Fight>();
            this.Fights2 = new HashSet<Fight>();
            this.Fights3 = new HashSet<Fight>();
        }
    
        public int ActorID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string SecondName { get; set; }
        public string Nickname { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> TitleID { get; set; }
    
        public virtual Title Title { get; set; }
        public virtual ICollection<AmateurFight> AmateurFights { get; set; }
        public virtual ICollection<ExibitionFight> ExibitionFights { get; set; }
        public virtual ICollection<Fight> Fights { get; set; }
        public virtual ICollection<Fight> Fights1 { get; set; }
        public virtual ICollection<Fight> Fights2 { get; set; }
        public virtual ICollection<Fight> Fights3 { get; set; }
    }
}
