//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliArchive.Repository.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AliDBContext : DbContext
    {
        public AliDBContext()
            : base("name=AliDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actors { get; set; }
        public virtual DbSet<AmateurFight> AmateurFights { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DeerLake> DeerLakes { get; set; }
        public virtual DbSet<ExibitionFight> ExibitionFights { get; set; }
        public virtual DbSet<Fact> Facts { get; set; }
        public virtual DbSet<Fight> Fights { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Quiz> Quizs { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<Venue> Venues { get; set; }
        public virtual DbSet<Belt> Belts { get; set; }
    }
}
