//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliArchive.Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExibitionFight
    {
        public int ExibitionFightID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> OpponentID { get; set; }
        public Nullable<int> VenueID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> Rounds { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual Venue Venue { get; set; }
    }
}
