//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliArchive.Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchJudge
    {
        public int FightID { get; set; }
        public int ActorID { get; set; }
        public string Score { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Fight Fight { get; set; }
    }
}
