//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliArchive.Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Round
    {
        public Round()
        {
            this.Fights = new HashSet<Fight>();
        }
    
        public int RoundID { get; set; }
        public Nullable<int> TotalNumberOfRounds { get; set; }
    
        public virtual ICollection<Fight> Fights { get; set; }
    }
}
